[settings]
python.uv_venv_auto = true

[tools]
uv = "0.9.26"
python = "3.14.2"
ruff = "0.14.13"

[tasks.sync]
run = ["uv sync --all-packages --extra dev", "cd packages/core && uv pip install -e ."]

[tasks.test]
dir = "packages/core"
run = "uv run pytest"

[tasks.pre-commit]
run = ["ruff format .", "ruff check --fix ."]

[tasks.lint]
run = "uv run mypy"
