[project]
name = "web"
version = "0.1.0"
description = "web interface for the calendario pkg"
requires-python = ">=3.11"
dependencies = [
    "flask",
    "calendario",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app/"]

[tool.uv.sources]
calendario = { workspace = true }
